-- Woburn Pickleball Crew - Supabase Database Setup
-- Copy and paste this entire script into your Supabase project's SQL Editor (https://supabase.com/dashboard/project/udcsdzholfmwyjddelum/sql) and click "Run".

-- 1. Create settings table
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Enable RLS and public access
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read settings" ON public.settings;
CREATE POLICY "Public read settings" ON public.settings FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public modify settings" ON public.settings;
CREATE POLICY "Public modify settings" ON public.settings FOR ALL USING (true);

-- Insert default settings
INSERT INTO public.settings (key, value) VALUES
('venmo_handle', 'LGoodrich401'),
('organizer_name', 'Lori'),
('cost_per_person', '23'),
('location', 'Woburn Racket Club, 9 Webster St, Woburn, MA 01801'),
('courts', '2'),
('time_slot', '7:00 PM - 9:00 PM'),
('default_max_players', '8')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- 2. Create sessions table
CREATE TABLE IF NOT EXISTS public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_date TEXT NOT NULL UNIQUE,
    day_of_week TEXT NOT NULL DEFAULT 'Thursday',
    time_slot TEXT NOT NULL DEFAULT '7:00 PM - 9:00 PM',
    location TEXT NOT NULL DEFAULT 'Woburn Racket Club, 9 Webster St, Woburn, MA 01801',
    courts INT NOT NULL DEFAULT 2,
    cost_per_person NUMERIC NOT NULL DEFAULT 23.00,
    max_players INT NOT NULL DEFAULT 8,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and public access
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read sessions" ON public.sessions;
CREATE POLICY "Public read sessions" ON public.sessions FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public modify sessions" ON public.sessions;
CREATE POLICY "Public modify sessions" ON public.sessions FOR ALL USING (true);

-- 3. Create signups table
CREATE TABLE IF NOT EXISTS public.signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES public.sessions(id) ON DELETE CASCADE,
    player_name TEXT NOT NULL,
    phone TEXT DEFAULT '',
    paid INT NOT NULL DEFAULT 0,
    paid_at TIMESTAMPTZ,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and public access
ALTER TABLE public.signups ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read signups" ON public.signups;
CREATE POLICY "Public read signups" ON public.signups FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public modify signups" ON public.signups;
CREATE POLICY "Public modify signups" ON public.signups FOR ALL USING (true);

-- 4. Pre-seed the 8 Thursday sessions (starting Oct 15th, skipping Thanksgiving)
INSERT INTO public.sessions (session_date, day_of_week, time_slot, location, courts, cost_per_person, max_players, notes)
VALUES
('2026-10-15', 'Thursday', '7:00 PM - 9:00 PM', 'Woburn Racket Club, 9 Webster St, Woburn, MA 01801', 2, 23.00, 8, 'Week 1 of 8 • 2 Courts reserved for doubles play!'),
('2026-10-22', 'Thursday', '7:00 PM - 9:00 PM', 'Woburn Racket Club, 9 Webster St, Woburn, MA 01801', 2, 23.00, 8, 'Week 2 of 8 • 2 Courts reserved for doubles play!'),
('2026-10-29', 'Thursday', '7:00 PM - 9:00 PM', 'Woburn Racket Club, 9 Webster St, Woburn, MA 01801', 2, 23.00, 8, 'Week 3 of 8 • 2 Courts reserved for doubles play!'),
('2026-11-05', 'Thursday', '7:00 PM - 9:00 PM', 'Woburn Racket Club, 9 Webster St, Woburn, MA 01801', 2, 23.00, 8, 'Week 4 of 8 • 2 Courts reserved for doubles play!'),
('2026-11-12', 'Thursday', '7:00 PM - 9:00 PM', 'Woburn Racket Club, 9 Webster St, Woburn, MA 01801', 2, 23.00, 8, 'Week 5 of 8 • 2 Courts reserved for doubles play!'),
('2026-11-19', 'Thursday', '7:00 PM - 9:00 PM', 'Woburn Racket Club, 9 Webster St, Woburn, MA 01801', 2, 23.00, 8, 'Week 6 of 8 • 2 Courts reserved for doubles play!'),
('2026-12-03', 'Thursday', '7:00 PM - 9:00 PM', 'Woburn Racket Club, 9 Webster St, Woburn, MA 01801', 2, 23.00, 8, 'Week 7 of 8 • 2 Courts reserved for doubles play!'),
('2026-12-10', 'Thursday', '7:00 PM - 9:00 PM', 'Woburn Racket Club, 9 Webster St, Woburn, MA 01801', 2, 23.00, 8, 'Week 8 of 8 • 2 Courts reserved for doubles play!')
ON CONFLICT (session_date) DO NOTHING;

-- Enable Realtime for live cross-device sync
ALTER PUBLICATION supabase_realtime ADD TABLE public.sessions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.signups;
ALTER PUBLICATION supabase_realtime ADD TABLE public.settings;
